**Future Skills**
1. Data
2. Software
3. Design

**Contents**
- review class OOP
- review loop + dictionary
- try except
- assert
- csv, json, context, manager
- web scraping
- numpy pandas sqlite aklearn

In [ ]:
# super class
class Person:
    def __init__(self, name):
        self.name = name
    def hey(self):
        print("Hello! world")
    def sayhi(self):
        print(f"Hi my name is {self.name}")

class Employee(Person): 
    def __init__(self, name, company):
        super().__init__(name)
        self.company = company
    def potato(self):
        print("Potato is very good")
    def sayhi(self):
        print(f"Hi my name is {self.name} and I work at {self.company}.")
# สิ่งที่อยู่ใน class จะอยู่ใน super class ด้วย แต่สิ่งที่อยู่ใน super class ไม่อยู่ใน class

In [ ]:
Nam = Person("Nam")
John = Employee("John", "Google")
Nam.sayhi()
John.sayhi()

Hi my name is Nam
Hi my name is John and I work at Google.


In [ ]:
Nam.hey()

Hello! world


In [ ]:
John.hey()
John.sayhi()
John.potato()

Hello! world
Hi my name is John and I work at Google.
Potato is very good


In [ ]:
# try-except block ใช้จัดการ error ให้ run จบ ค่อยมาดู error ย้อนหลัง
try:
    1/0
except:
    print("this is an error message")

this is an error message


In [ ]:
# error มีหลายแบบ
try:
    print("hello")
except ZeroDivisionError:
    print("Cannot divide a number with zero.")
except NameError:
    print("Variable is not found.")
except ValueError:
    print("Please check your data type again.")
else:
    print("Done!")
finally:
    print("This is the last line")

hello
Done!
This is the last line


In [ ]:
# assert หลังคำนี้ ไม่มี error มันเช็คว่าเป็นจริงมั้ย 
assert 1+1 == 5, "1+1 must be equal 2" # เขียนบอก error

AssertionError: ignored

In [ ]:
def check_this(a, b):
    assert a+b > 10, "a+b should be more than ten"
    return a+b

In [ ]:
check_this(10, 20)

30

In [ ]:
# lambda function
# ปกติ 
def greeting(name):
    print("hello! " + name)

In [ ]:
# lambda
greeting = lambda name: print("hello! " + name)

In [ ]:
greeting("Nam")

hello! Nam


In [ ]:
def odd_or_even(num):
    if num % 2 == 0:
        print("Even")
    else: 
        print("Odd")

In [ ]:
odd_or_even(5)

Odd


In [ ]:
odd_or_even = lambda num: "even" if num % 2 == 0 else "odd"
# lambda simple function

In [ ]:
odd_or_even(4)

'even'

In [ ]:
#  dictionary
# list of colored balls
balls = ['red', 'red', 'green', 'blue', 'blue']

In [ ]:
def summary(lst_items):
    result = {} # empty dict
    for item in lst_items:
        if item in result:
            result[item] += 1
        else:
            result[item] = 1

print(result)

{'red': 2, 'green': 1, 'blue': 2}


In [ ]:
# comma separated values (csv file)


In [82]:
!ls # เรียกดู ชื่อไฟล์
!mkdir newFolder # create file
!rmdir newFolder # remove file

'Ex. hotel.csv'   name.json	     sample_data
 imdb_data.csv	  newjsonfile.json   starwarapi.csv


In [83]:
! echo hello

hello


In [84]:
!cat Ex.\ hotel.csv

id,hotel,location,price
1,Accor,Thailand,50
2,Ibis,Italy,60
3,London,UK,35
4,Seoul,Korea,30
5,Ie Concord,USA,25


In [92]:
# read csv
import csv

file = open("Ex. hotel.csv")

data = csv.reader(file)

for row in data:
    print(row)

file.close()

['\ufeffid', 'hotel', 'location', 'price']
['1', 'Accor', 'Thailand', '50']
['2', 'Ibis', 'Italy', '60']
['3', 'London', 'UK', '35']
['4', 'Seoul', 'Korea', '30']
['5', 'Ie Concord', 'USA', '25']


In [86]:
# context manager
import csv

try:
    with open("Ex. Hotel.csv", "r") as file:
        data = csv.reader(file)
        for row in data:
            print(row)
except: 
    print("Found some error, please check again.")

Found some error, please check again.


In [87]:
#modern python
import pandas as pd

df = pd.read_csv("Ex. hotel.csv")

df["price_double"] = df["price"]*2

df.to_csv("Ex. hotel_modified.csv")
df

id       hotel  location  price  price_double
0   1       Accor  Thailand     50           100
1   2        Ibis     Italy     60           120
2   3      London        UK     35            70
3   4       Seoul     Korea     30            60
4   5  Ie Concord       USA     25            50

In [88]:
# write csv file
# "w" write mode
import csv

headers = ["id", "name", "age"]
data = [
    [1, "nam", 22],
    [2, "first", 23],
    [3, "john", 32]
]

with open("newfile.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(headers)
    writer.writerows(data)

In [89]:
!cat newfile.csv

id,name,age
1,nam,22
2,first,23
3,john,32


In [90]:
result = []
with open("newfile.csv", "r") as file:
    data = csv.reader(file)
    for row in data:
        result.append(row)
print(result)

[['id', 'name', 'age'], ['1', 'nam', '22'], ['2', 'first', '23'], ['3', 'john', '32']]


In [ ]:
# regular espression

# import re ถ้าใช้ตัวนี้ ต้อง re.search [line 8]
from re import search

text = "a duck walks into a bar"

search("duck", text)[0] # duck ตัวที่ 1 
result = search("duck", text)
if result:
    print("Duck Found")
else:
    print("Duck not Found")


Duck Found


In [ ]:
# list comprehension
numbers = [1,2,3,4,5]
result = [num*2 for num in numbers]
print(result)

[2, 4, 6, 8, 10]


In [ ]:
even_nums = []
for num in numbers:
    if num % 2 == 1:
        even_nums.append(num)
print(even_nums)

[1, 3, 5]


In [ ]:
oddNums = [num for num in numbers if num%2 == 1]
evenNums = [num for num in numbers if num%2 == 0]
print(oddNums, evenNums) 

[1, 3, 5] [2, 4]


In [ ]:
## json => JavaScript Object Notation
import json
with open("name.json", "r") as f:
    data = json.load(f)
data

{'name': 'Nam',
 'age': 22,
 'movie_lover': True,
 'movies': ['batman', 'superman']}

In [ ]:
data["movies"][0]

'batman'

In [ ]:
# create new .json file
school = {
    "name": "bootcamp",
    "batch": 7,
    "duration": "4 months"
}

with open("newjsonfile.json", "w") as file:
    json.dump(school, file)

In [ ]:
!cat newjsonfile.json

{"name": "bootcamp", "batch": 7, "duration": "4 months"}

In [ ]:
with open("newjsonfile.json", "r") as file:
    result = json.load(file)
result

{'name': 'bootcamp', 'batch': 7, 'duration': '4 months'}

In [15]:
# API get request สำคัญมาก
import requests

url = "https://swapi.dev/api/people/1"

result = requests.get(url)
data = result.json()
data["name"]

'Luke Skywalker'

In [16]:
# find public API 

In [19]:
import requests
from time import sleep # ให้มันได้พัก ไม่งั้นจะล่มได้ 

nums = list(range(1,6))

result = []

for i in nums:
    url = f"https://swapi.dev/api/people/{i}"
    response = requests.get(url)
    data = response.json()
    row = [
        data["name"],
        data["height"],
        data["mass"],
        data["gender"]
    ]
    result.append(row)
    print(result)
    sleep(1) # second




[['Luke Skywalker', '172', '77', 'male']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male'], ['Leia Organa', '150', '49', 'female']]


In [22]:
# create dataframe
import pandas as pd

df = pd.DataFrame(result, columns = ["name", "height", "mass", "gender"])

df.to_csv("starwarapi.csv") # create file is csv

## Web Scraping

In [24]:
# web scraping
# gazpacho
!pip install gazpacho # ติดตั้ง

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7480 sha256=de0c6077a9725e647484e6dead34b721c7659c2e2f2315de72a4af9c63610c2d
  Stored in directory: /root/.cache/pip/wheels/9b/bf/9f/8c8849499462415fa5cdf0d9edb1103c189bdbece90c51488e
Successfully built gazpacho


In [25]:
!pip list | grep "gaz"

gazpacho                      1.1


In [28]:
from gazpacho import Soup
from requests import get

url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

response = get(url)

imdb = Soup(response.text) # Soup จะค้นหาคำนั้นๆได้

In [36]:
imdb.find("h3")[10].strip() # .strip() ลบอักขระพิเศษออก
# find หาคำที่อยู่ใน ""

'11. The Lord of the Rings: The Fellowship of the Ring (2001)'

In [38]:
title_list = imdb.find("h3", {"class": "lister-item-header"})

In [39]:
for title in title_list:
    print(title.strip())

1. The Shawshank Redemption (1994)
2. The Godfather (1972)
3. The Dark Knight (2008)
4. Schindler's List (1993)
5. The Lord of the Rings: The Return of the King (2003)
6. 12 Angry Men (1957)
7. The Godfather Part II (1974)
8. Pulp Fiction (1994)
9. Inception (2010)
10. Fight Club (1999)
11. The Lord of the Rings: The Fellowship of the Ring (2001)
12. Forrest Gump (1994)
13. The Good, the Bad and the Ugly (1966)
14. The Lord of the Rings: The Two Towers (2002)
15. The Matrix (1999)
16. Goodfellas (1990)
17. One Flew Over the Cuckoo's Nest (1975)
18. Star Wars: Episode V - The Empire Strikes Back (1980)
19. Interstellar (2014)
20. The Silence of the Lambs (1991)
21. Se7en (1995)
22. Star Wars (1977)
23. The Green Mile (1999)
24. Spirited Away (2001)
25. Saving Private Ryan (1998)
26. Terminator 2: Judgment Day (1991)
27. City of God (2002)
28. Life Is Beautiful (1997)
29. Seven Samurai (1954)
30. It's a Wonderful Life (1946)
31. Harakiri (1962)
32. Alien (1979)
33. Whiplash (2014)
34. Gl

In [54]:
titles = [title.strip() for title in title_list]
print(titles)

['1. The Shawshank Redemption (1994)', '2. The Godfather (1972)', '3. The Dark Knight (2008)', "4. Schindler's List (1993)", '5. The Lord of the Rings: The Return of the King (2003)', '6. 12 Angry Men (1957)', '7. The Godfather Part II (1974)', '8. Pulp Fiction (1994)', '9. Inception (2010)', '10. Fight Club (1999)', '11. The Lord of the Rings: The Fellowship of the Ring (2001)', '12. Forrest Gump (1994)', '13. The Good, the Bad and the Ugly (1966)', '14. The Lord of the Rings: The Two Towers (2002)', '15. The Matrix (1999)', '16. Goodfellas (1990)', "17. One Flew Over the Cuckoo's Nest (1975)", '18. Star Wars: Episode V - The Empire Strikes Back (1980)', '19. Interstellar (2014)', '20. The Silence of the Lambs (1991)', '21. Se7en (1995)', '22. Star Wars (1977)', '23. The Green Mile (1999)', '24. Spirited Away (2001)', '25. Saving Private Ryan (1998)', '26. Terminator 2: Judgment Day (1991)', '27. City of God (2002)', '28. Life Is Beautiful (1997)', '29. Seven Samurai (1954)', "30. It'

In [50]:
runtimes = imdb.find("span", {"class": "runtime"})
runtimes = [runtime.strip() for runtime in runtimes]
print(runtimes)

['142 min', '175 min', '152 min', '195 min', '201 min', '96 min', '202 min', '154 min', '148 min', '139 min', '178 min', '142 min', '178 min', '179 min', '136 min', '145 min', '133 min', '124 min', '169 min', '118 min', '127 min', '121 min', '189 min', '125 min', '169 min', '137 min', '130 min', '116 min', '207 min', '130 min', '133 min', '117 min', '106 min', '155 min', '132 min', '116 min', '151 min', '130 min', '110 min', '88 min', '150 min', '109 min', '106 min', '102 min', '119 min', '112 min', '165 min', '89 min', '155 min', '112 min']


In [56]:
import pandas as pd

df = pd.DataFrame({
    "title": titles,
    "runtime": runtimes
})

df.head()

title  runtime
0                 1. The Shawshank Redemption (1994)  142 min
1                            2. The Godfather (1972)  175 min
2                          3. The Dark Knight (2008)  152 min
3                         4. Schindler's List (1993)  195 min
4  5. The Lord of the Rings: The Return of the Ki...  201 min

In [57]:
df.to_csv("imdb_data.csv")

# Basic Data Tools

- numpy
- pandas
- sklearn

In [61]:
# numpy => numerical python
import numpy as np

num = [1, 2 , 3, 4, 5]
num * 2


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [62]:
[x*2 for x in num] # ต่างกันกับ x * 2

[2, 4, 6, 8, 10]

In [63]:
# numpy => numerical python
import numpy as np

num = [1, 2 , 3, 4, 5]

num_arr = np.array(num)

In [65]:
print(num_arr * 2, num_arr + 2, num_arr - 2, num_arr / 2)

[ 2  4  6  8 10] [3 4 5 6 7] [-1  0  1  2  3] [0.5 1.  1.5 2.  2.5]


In [68]:
# statistical basic calculation
np.sum(num_arr)
np.mean(num_arr)
np.median(num_arr)
np.std(num_arr)
np.min(num_arr)
np.max(num_arr)
len(num_arr)

5

In [67]:
num_arr.sum() # เขียนแบบนี้ก็ได้ แต่บางอันก็ใช้ไม่ได้

15

In [71]:
# matrix 2D-array
m1 = np.array([
    [1, 2],
    [3, 4]
])

In [72]:
m1

array([[1, 2],
       [3, 4]])

In [73]:
m1 + 2

array([[3, 4],
       [5, 6]])

In [74]:
m2 = np.array([
    [5, 5],
    [4, 2]
])

In [78]:
print(m1, "\n"*2, m2)

[[1 2]
 [3 4]] 

 [[5 5]
 [4 2]]


In [79]:
m1 * m2 # ผิด

array([[ 5, 10],
       [12,  8]])

In [80]:
m1.dot(m2)

array([[13,  9],
       [31, 23]])

In [81]:
np.dot(m1, m2)

array([[13,  9],
       [31, 23]])

In [5]:
# intro to pandas
# โหลดคู่กัน 
import pandas as pd
import numpy as np 

In [7]:
hotel = pd.read_csv("Ex. hotel.csv")

In [8]:
hotel

id       hotel  location  price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     35
3   4       Seoul     Korea     30
4   5  Ie Concord       USA     25

In [9]:
hotel.shape # (row, col)

(5, 4)

In [10]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        5 non-null      int64 
 1   hotel     5 non-null      object
 2   location  5 non-null      object
 3   price     5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes


In [11]:
hotel.describe(include="all")

id  hotel  location     price
count   5.000000      5         5   5.00000
unique       NaN      5         5       NaN
top          NaN  Accor  Thailand       NaN
freq         NaN      1         1       NaN
mean    3.000000    NaN       NaN  40.00000
std     1.581139    NaN       NaN  14.57738
min     1.000000    NaN       NaN  25.00000
25%     2.000000    NaN       NaN  30.00000
50%     3.000000    NaN       NaN  35.00000
75%     4.000000    NaN       NaN  50.00000
max     5.000000    NaN       NaN  60.00000

In [12]:
hotel["location"] # ใช้ hotel.location แบบนี้ก็ได้ แต่ถ้าชื่อ มีเว้นวรรค ให้ใช้ []

0    Thailand
1       Italy
2          UK
3       Korea
4         USA
Name: location, dtype: object

In [13]:
# create column
hotel["vat"] = hotel["price"] * 0.07

In [14]:
hotel

id       hotel  location  price   vat
0   1       Accor  Thailand     50  3.50
1   2        Ibis     Italy     60  4.20
2   3      London        UK     35  2.45
3   4       Seoul     Korea     30  2.10
4   5  Ie Concord       USA     25  1.75

In [15]:
# query (filter rows)
value_hotel = hotel.query( "price > 40" )

In [16]:
value_hotel.to_csv("value_hotel.csv")

In [17]:
# drop column
new_hotel = hotel.drop("vat", axis=1)

In [18]:
new_hotel

id       hotel  location  price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     35
3   4       Seoul     Korea     30
4   5  Ie Concord       USA     25

In [19]:
hotel.drop("vat", axis=1, inplace=True) #  ลบแบบไม่ต้องประกาศค่าใหม่
hotel

id       hotel  location  price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     35
3   4       Seoul     Korea     30
4   5  Ie Concord       USA     25

In [20]:
hotel.query( " price < 40 and location == 'UK' ")

id   hotel location  price
2   3  London       UK     35

In [116]:
# sklearn => machine learning most popular python
# template in sklearn to train_test_split

In [117]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd

In [123]:
mtcars = pd.read_csv("http://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv")

In [126]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [130]:
# prepare 50-80%
X = mtcars[ ["hp", "wt", "am"] ]
y = mtcars[ "mpg" ]

In [134]:
# split data 80% train, 20% test
# ส่ง data มา 4 ส่วน
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=42)

In [141]:
# train model
model = LinearRegression()
model.fit(X_train, y_train)

# test model / scoring
pred = model.predict(X_test)
# MAE mean absolute error
mae = np.mean(np.absolute((y_test - pred)))

# evaluate model
# MSE
mse = np.mean((y_test - pred)**2)

print(mae, mse)



2.0710117400488417 7.319771016726086
